/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const logError: typeof import('./src/utils/logger').logError
  const logMessage: typeof import('./src/utils/logger').logMessage
  const useErrorLogger: typeof import('./src/composables/useErrorLogger').useErrorLogger
}
